#Dockercompose
version: '3.6'
services:
  datab:
    image: 'mariadb:10.4'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
  adminer:
      image: 'adminer:4.7'
      ports:
        - 50000:8080
  php-apache:
    build: './docker/php'
    container_name: php_web
    restart: always
    depends_on:
      - datab
    volumes:
      - ./php:/var/www/html/
    ports:
      - 30000:80
  