#Dockercompose
version: '3.6'
services:
  datab:
    image: 'mariadb:10.4'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - 30000:80
  php:
    build: './docker/php'
    container_name: php_web
    restart: always
    depends_on:
      - datab
    volumes:
     - ./php/:/var/www/html/
  adminer:
    image: 'adminer:4.7'
    restart: always
    ports:
      - 50000:8080